## ──────────────────────────────────────────────
## ExternalSecret: RDS credentials (managed by AWS RDS)
## ──────────────────────────────────────────────
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: targeting-service-rds
  namespace: togglemaster-targeting
  labels:
    app.kubernetes.io/name: targeting-service
    app.kubernetes.io/component: targeting
    app.kubernetes.io/part-of: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-us-east-1
    kind: SecretStore
  target:
    name: targeting-service-rds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: rds!db-cb7e8ccf-f102-494d-afc0-4f7f90a0590a
        property: username
    - secretKey: password
      remoteRef:
        key: rds!db-cb7e8ccf-f102-494d-afc0-4f7f90a0590a
        property: password
---
## ──────────────────────────────────────────────
## ExternalSecret: Targeting service config
## Source: togglemaster/targeting-service (AWS Secrets Manager)
## Creates K8s Secret: targeting-service-config
## ──────────────────────────────────────────────
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: targeting-service-config
  namespace: togglemaster-targeting
  labels:
    app.kubernetes.io/name: targeting-service
    app.kubernetes.io/component: targeting
    app.kubernetes.io/part-of: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-us-east-1
    kind: SecretStore
  target:
    name: targeting-service-config
    creationPolicy: Owner
  data:
    - secretKey: TARGETING_DB_HOST
      remoteRef:
        key: togglemaster/targeting-service
        property: TARGETING_DB_HOST
    - secretKey: TARGETING_DB_NAME
      remoteRef:
        key: togglemaster/targeting-service
        property: TARGETING_DB_NAME
    - secretKey: TARGETING_DB_PORT
      remoteRef:
        key: togglemaster/targeting-service
        property: TARGETING_DB_PORT
    - secretKey: AUTH_SERVICE_URL
      remoteRef:
        key: togglemaster/targeting-service
        property: AUTH_SERVICE_URL
    - secretKey: FLAG_SERVICE_URL
      remoteRef:
        key: togglemaster/targeting-service
        property: FLAG_SERVICE_URL