## ──────────────────────────────────────────────
## ExternalSecret: RDS credentials (managed by AWS RDS)
## ──────────────────────────────────────────────
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flag-service-rds
  namespace: togglemaster-flag
  labels:
    app.kubernetes.io/name: flag-service
    app.kubernetes.io/component: flag
    app.kubernetes.io/part-of: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-us-east-1
    kind: SecretStore
  target:
    name: flag-service-rds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: rds!db-256f4b5b-c5d7-40f8-8cdd-504646c98c28
        property: username
    - secretKey: password
      remoteRef:
        key: rds!db-256f4b5b-c5d7-40f8-8cdd-504646c98c28
        property: password
---
## ──────────────────────────────────────────────
## ExternalSecret: Flag service config
## Source: togglemaster/flag-service (AWS Secrets Manager)
## Creates K8s Secret: flag-service-config
## ──────────────────────────────────────────────
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flag-service-config
  namespace: togglemaster-flag
  labels:
    app.kubernetes.io/name: flag-service
    app.kubernetes.io/component: flag
    app.kubernetes.io/part-of: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-us-east-1
    kind: SecretStore
  target:
    name: flag-service-config
    creationPolicy: Owner
  data:
    - secretKey: FLAG_DB_HOST
      remoteRef:
        key: togglemaster/flag-service
        property: FLAG_DB_HOST
    - secretKey: FLAG_DB_NAME
      remoteRef:
        key: togglemaster/flag-service
        property: FLAG_DB_NAME
    - secretKey: FLAG_DB_PORT
      remoteRef:
        key: togglemaster/flag-service
        property: FLAG_DB_PORT
    - secretKey: AUTH_SERVICE_URL
      remoteRef:
        key: togglemaster/flag-service
        property: AUTH_SERVICE_URL