apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager-us-east-1
  namespace: togglemaster-targeting
  labels:
    app.kubernetes.io/name: targeting-service
    app.kubernetes.io/component: targeting
    app.kubernetes.io/part-of: togglemaster
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: access-key
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret-access-key
          sessionTokenSecretRef:
            name: aws-credentials
            key: session-token